# Generated by Django 4.2.4 on 2023-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_img', models.URLField()),
                ('project_link', models.URLField(default='#', null=True)),
                ('project_code', models.URLField(default='#', null=True)),
                ('skill_used', models.ManyToManyField(related_name='project_skill', to='portfolio.skill')),
            ],
        ),
    ]
